name: HSON test

on:
  push:
    paths:
      - "**/*.go"
      - .github/workflows/go.yml
    branches:
      - main

jobs:    
  pkgtest:
    name: Package test
    strategy:
      matrix:
        pkgpath:
          - file
          - structre
        os:
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.pkgpath }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ">=1.17.2 <1.18.0"
      - name: Get packages
        run: go mod download
      - name: Run test
        run: go test


    
