# Release HSON dynamic library as artific
# These compiled libraries are AMD64 based
# For other arch like Raspberry Pi or Mac which run on Apple Silicon, please do it by yourself

name: HSON build release
on:
  push:
    branches:
      - release
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/release.yml"
env:
  CGO_ENABLED: 1
jobs:
  release:
    name: Compile HSON (AMD64)
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ">=1.17.2 <1.18.0"
      - name: Get packages
        run: go mod download
      - name: Compile to library
        run: make build
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: hson-${{ matrix.os }}
          path: bin
          retention-days: 7
  linux-arm64-release:
    needs: release
    name: Compile HSON for Linxu (ARM64)
    runs-on: ubuntu-latest
    env:
      GOARCH: arm64
      CC: aarch64-linux-gnu-gcc
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Get cross compiler for ARM
        run: sudo apt install gcc-aarch64-linux-gnu -y
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ">=1.17.2 <1.18.0"
      - name: Get packages
        run: go mod download
      - name: Compile to library
        run: go build -buildmode c-shared -o bin/hson_linux_arm64.so main.go
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: hson-${{ matrix.os }}-arm64
          path: bin
          retention-days: 7
  # m1-release:
  #   name: Compile HSON for Apple Silicon (ARM64)
  #   runs-on: macos-11
  #   steps:
  #     - uses: actions/checkout@v2.3.5
  #     - uses: actions/setup-go@v2.1.4
  #       with:
  #         go-version: ">=1.17.2 <1.18.0"
  #     - name: Get packages
  #       run: go mod download
  #     - name: Compile to library
  #       run: make build
  #     - name: Upload to artifacts
  #       uses: actions/upload-artifact@v2.2.4
  #       with:
  #         name: hson-${{ matrix.os }}
  #         path: bin
  #         retention-days: 7        

        
    