# Release HSON dynamic library as artific
# These compiled libraries are AMD64 based
# For other arch like Raspberry Pi or Mac which run on Apple Silicon, please do it by yourself

name: HSON build release
on:
  push:
    branches:
      - release
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/release.yml"
env:
  CGO_ENABLED: 1
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ">=1.17.2 <1.18.0"
      - name: Get packages
        run: go mod download
      - name: Compile to library
        run: make build
      - name: Archive as zip
        run: 7z a -tzip hson-${{ matrix.os }}.zip bin/*.*
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: hson-${{ matrix.os }}
          path: hson-${{ matrix.os }}.zip
          retention-days: 7
        

        
    